#!/bin/sh

if [ "${1:-}" = remove ] || [ "${1:-}" = deconfigure ]; then
    if [ -x /usr/bin/launchctl ]; then
        /usr/bin/launchctl bootout system/wiki.qaq.cocoainspectord 2>/dev/null || true
    fi
    uicache=/usr/bin/uicache
    if [ -x "$uicache" ]; then
        "$uicache" -u wiki.qaq.Inspector || true
    fi
fi

exit 0
